### ISSUE TITLE
plot recipe for unbounded HPolyhedron 

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/LazySets.jl#1611] opened 2019-08-16 08:32 UTC
I'd like to add a plot recipe for an unbounded `HPolyhedron` in 2D and 3D. 
There is a problem with how much of the unbounded part should be plotted and how could it be updated if the limit of the plot changes, otherwise I think it should be not too hard.

Did you already think about doing this? If so, do you have any pointers on how to start?

**Comment by schillic** [comment] 2019-08-16 08:37
> Did you already think about doing this?

Yes, see #576.

> There is a problem with how much of the unbounded part should be plotted

Indeed, and I do not have a solution for that (see the other issue for a hack).

**Comment by ueliwechsler** [comment] 2019-08-16 08:50
Sorry, I did not go through the entire issue history and I see, the problem is harder than I initially thought 🙈.

My spontaneous idea for the 2D case would be to add four constraints `x1 <= M`, `x1 >= -M`, x2 <= M`, `x2 >= -M` where `M` is large in order to get a bounded `HPolyhedra`  and then we could use the recipe for the bounded case. The last thing to do would be to set the axis limits accordingly.

**Comment by schillic** [comment] 2019-08-17 13:27
Yes, this is a good idea and I think it should work for all unbounded set types. Therefore, I will close this as a duplicate of #576.

**Closed by schillic** 2019-08-17 13:27 UTC
