### ISSUE TITLE
Add getter function for center at a specific index for hyperrectangular sets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1969] opened 2020-02-16 00:07 UTC
`center(H)[i]` (use in `AbstractHyperrectangle.jl` for example) allocates a vector; we should consider a better fallback requiring `center(H::AbstractHyperrectangle, i::Int)` to be part of the `AbstractHyperrectangle` interface and use it.

**Comment by schillic** [comment] 2020-02-17 15:18
duplicate of #1578

**Closed by schillic** 2020-02-17 15:18 UTC
Labels: duplicate

**Comment by mforets** [comment] 2020-02-17 15:34
Ooops, i didn't see the other issue, thanks.
