### ISSUE TITLE
Add template directions alias symbols

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1329] opened 2019-05-01 18:11 UTC
Proposal: bring the following aliases from Reachability.jl (see [here](https://github.com/JuliaReach/Reachability.jl/blob/master/src/Utils/Utils.jl#L386)):

```julia
template_direction_symbols = Dict(
    :box     => Approximations.BoxDirections,
    :oct     => Approximations.OctDirections,
    :boxdiag => Approximations.BoxDiagDirections
    )
```

**Comment by schillic** [comment] 2020-07-18 16:21
Duplicate of #339.

**Closed by schillic** 2020-07-18 16:21 UTC
Labels: usability :computer_mouse:
