### ISSUE TITLE
Undefined LP in remove_redundant_constraints

### ISSUE THREAD

**Issue by dfcaporale** [JuliaReach/LazySets.jl#2732] opened 2021-06-07 13:51 UTC
```julia
C = HPolytope{Float64, Vector{Float64}}(HalfSpace{Float64, Vector{Float64}}[HalfSpace{Float64, Vector{Float64}}([0.0010489971808121915, 0.02305738123969779, 0.05246734737789573, 0.9983558655281237, -0.0], 3.5385670032695807e-8), HalfSpace{Float64, Vector{Float64}}([0.019968613131868013, -0.0012136033332396461, 0.9984167150676541, -0.05257228100486211, 0.0], 6.750869641201481e-8), HalfSpace{Float64, Vector{Float64}}([-0.019968613131868013, 0.0012136033332396461, -0.9984167150676541, 0.05257228100486211, -0.0], -1.0221666834247359e-9), HalfSpace{Float64, Vector{Float64}}([-0.0010489971808121915, -0.02305738123969779, -0.05246734737789573, -0.9983558655281237, 0.0], -3.5385670032695807e-8), HalfSpace{Float64, Vector{Float64}}([-0.019968613131868013, 0.0012136033332396461, -0.9984167150676541, 0.05257228100486211, -0.0], -6.750869641201481e-8), HalfSpace{Float64, Vector{Float64}}([0.019968613131868013, -0.0012136033332396461, 0.9984167150676541, -0.05257228100486211, 0.0], 1.0221666834247359e-9), HalfSpace{Float64, Vector{Float64}}([0.0, -0.0, 0.0, -0.0, 1.0], 6.040000000000004), HalfSpace{Float64, Vector{Float64}}([-0.0, 0.0, -0.0, 0.0, -1.0], -6.0000000000000036), HalfSpace{Float64, Vector{Float64}}([0.0009882838504617075, 0.02306085481512719, 0.049431723254901035, 0.9985107535756825, 0.0], 3.8000782892713374e-5), HalfSpace{Float64, Vector{Float64}}([-0.019971621703763997, 0.001143376530852595, -0.9985722070888599, 0.0495315479902816, 0.0], -7.829966237573391e-5), HalfSpace{Float64, Vector{Float64}}([1.0, 0.0, 0.0, 0.0, 0.0], -100.0)])
```

```julia
@show isbounded(C)
@show ρ([1,0,0,0,0], C)
@show ρ([-1,0,0,0,0], C)
```

isbounded(C) = true
ρ([1, 0, 0, 0, 0], C) = -100.0

the support function in direction [-1, 0, 0, 0, 0] is undefined because the polytope is unbounded

Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] ρ(d::Vector{Int64}, P::HPolytope{Float64, Vector{Float64}}; solver::GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP)
   @ LazySets ~\.julia\dev\LazySets\src\Sets\HPolyhedron.jl:113
 [3] ρ(d::Vector{Int64}, P::HPolytope{Float64, Vector{Float64}})
   @ LazySets ~\.julia\dev\LazySets\src\Sets\HPolyhedron.jl:110
 [4] top-level scope
   @ show.jl:955
 [5] eval
   @ .\boot.jl:360 [inlined]
 [6] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094

**Comment by mforets** [comment] 2021-06-07 13:54
Hmm I can't easily copy paste in the REPL... Can you paste the HPolytope otherwise? Or store it in another format? (eg. `tosmplehrep` -> MAT)

**Comment by schillic** [comment] 2021-06-07 13:55
I think your input is not bounded. `HPolytope` is a type that assumes boundedness, so `isbounded` returns `true` without checking. Create an `HPolyhedron` instead.

```julia
julia> C = C = HPolytope([HalfSpace([0.0010489971808121915, 0.02305738123969779, 0.05246734737789573, 0.9983558655281237, -0.0], 3.5385670032695807e-8), HalfSpace([0.019968613131868013, -0.0012136033332396461, 0.9984167150676541, -0.05257228100486211, 0.0], 6.750869641201481e-8), HalfSpace([-0.019968613131868013, 0.0012136033332396461, -0.9984167150676541, 0.05257228100486211, -0.0], -1.0221666834247359e-9), HalfSpace([-0.0010489971808121915, -0.02305738123969779, -0.05246734737789573, -0.9983558655281237, 0.0], -3.5385670032695807e-8), HalfSpace([-0.019968613131868013, 0.0012136033332396461, -0.9984167150676541, 0.05257228100486211, -0.0], -6.750869641201481e-8), HalfSpace([0.019968613131868013, -0.0012136033332396461, 0.9984167150676541, -0.05257228100486211, 0.0], 1.0221666834247359e-9), HalfSpace([0.0, -0.0, 0.0, -0.0, 1.0], 6.040000000000004), HalfSpace([-0.0, 0.0, -0.0, 0.0, -1.0], -6.0000000000000036), HalfSpace([0.0009882838504617075, 0.02306085481512719, 0.049431723254901035, 0.9985107535756825, 0.0], 3.8000782892713374e-5), HalfSpace([-0.019971621703763997, 0.001143376530852595, -0.9985722070888599, 0.0495315479902816, 0.0], -7.829966237573391e-5), HalfSpace([1.0, 0.0, 0.0, 0.0, 0.0], -100.0)])

julia> D = convert(HPolyhedron, C)

julia> isbounded(D)
false
```

**Comment by dfcaporale** [comment] 2021-06-07 14:21
Thanks, @schillic! 

Now I have an issue regarding the intersection of a (bounded) Zonotope Z with a HalfSpace I⁻.

```julia
I⁻ = LazySets.HalfSpace([1.0,0,0,0,0], -100.0)

c = [-803.4493071473623, -350.84919017994514, 16.06939562995633, 8.10268294907005, 6.020000000000004];
G = [22.3666        0.000478203   0.331469      0.000542754  0.0
     -0.000422096  21.9606       -0.000997406   0.174057     0.0
     -0.447337     -2.21122e-5   -0.00662942   -1.09537e-5   0.0
      1.78901e-5   -0.507187      2.31543e-5   -0.0040199    0.0
      0.0           0.0           0.0           0.0          0.02]
Z = Zonotope(c,G)

@show isbounded(Z)
@show ρ([ 1,0,0,0,0], Z)
@show ρ([-1,0,0,0,0], Z);
```

```julia
isbounded(Z) = true
ρ([1, 0, 0, 0, 0], Z) = -780.7502171903624
```

Then, I expect Z to be fully included in I⁻, and then their intersection should be equal to Z.

```julia
aux = intersection(Z, I⁻)

@show isbounded(aux)
@show ρ([ 1.0,0,0,0,0], aux)
@show ρ([-1.0,0,0,0,0], aux);
```

Error: primal simplex failed

LP is not optimal; the status of the LP is Undefined

Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] remove_redundant_constraints!(constraints::Vector{HalfSpace{Float64, Vector{Float64}}}; backend::GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP)
   @ LazySets ~\.julia\dev\LazySets\src\Interfaces\AbstractPolyhedron_functions.jl:236
 [3] #remove_redundant_constraints!#143
   @ ~\.julia\dev\LazySets\src\Sets\HPolyhedron.jl:378 [inlined]
 [4] intersection(P1::Zonotope{Float64, Vector{Float64}, Matrix{Float64}}, P2::HalfSpace{Float64, Vector{Float64}}; backend::GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP)
   @ LazySets ~\.julia\dev\LazySets\src\ConcreteOperations\intersection.jl:661
 [5] intersection(P1::Zonotope{Float64, Vector{Float64}, Matrix{Float64}}, P2::HalfSpace{Float64, Vector{Float64}})
   @ LazySets ~\.julia\dev\LazySets\src\ConcreteOperations\intersection.jl:649
 [6] top-level scope
   @ In[96]:3
 [7] eval
   @ .\boot.jl:360 [inlined]
 [8] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094

**Comment by mforets** [comment] 2021-06-07 14:24
I can reproduce; the error is actually in computing the list of constraints of the zonotope:

```julia
julia> remove_redundant_constraints(constraints_list(Z))
Error: primal simplex failed

ERROR: LP is not optimal; the status of the LP is Undefined
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] remove_redundant_constraints!(constraints::Vector{HalfSpace{Float64, Vector{Float64}}}; backend::GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP)
   @ LazySets ~/.julia/dev/LazySets/src/Interfaces/AbstractPolyhedron_functions.jl:236
 [3] #remove_redundant_constraints#50
   @ ~/.julia/dev/LazySets/src/Interfaces/AbstractPolyhedron_functions.jl:268 [inlined]
 [4] remove_redundant_constraints(constraints::Vector{HalfSpace{Float64, Vector{Float64}}})
   @ LazySets ~/.julia/dev/LazySets/src/Interfaces/AbstractPolyhedron_functions.jl:267
 [5] top-level scope
   @ REPL[39]:1
```

**Comment by schillic** [comment] 2021-06-07 14:29
I suggest that in `intersection` we first do two quick checks: `isdisjoint` and `issubset`. These are efficient. In both cases we can return a simpler set representation (the empty set resp. the input zonotope).

This solves the problem at hand but of course does not address the crash.

**Comment by mforets** [comment] 2021-06-07 14:33
Interseting idea; at leat for the types considered  (zonotope, halfspace) it's cheap.

**Comment by schillic** [comment] 2021-06-07 14:34
Yes, the comment was only meant for this combination.

**Comment by schillic** [comment] 2021-06-07 18:40
@SebastianGuadalupe added this idea in #2733 :tada:

**Comment by schillic** [comment] 2021-09-20 20:41
I do not fully understand the implementation anymore. It might be bugged.

https://github.com/JuliaReach/LazySets.jl/blob/a40b78b1920e9c0851978890f39c5fc95ac7a985/src/Interfaces/AbstractPolyhedron_functions.jl#L224-L233

There are indices `i` and `j` but they may not be changed consistently.

**Comment by schillic** [comment] 2022-12-15 21:52
For the record, this is the problem in this issue:

```julia
julia> c = [-803.4493071473623, -350.84919017994514, 16.06939562995633, 8.10268294907005, 6.020000000000004];
julia> G = [22.3666        0.000478203   0.331469      0.000542754  0.0
     -0.000422096  21.9606       -0.000997406   0.174057     0.0
     -0.447337     -2.21122e-5   -0.00662942   -1.09537e-5   0.0
      1.78901e-5   -0.507187      2.31543e-5   -0.0040199    0.0
      0.0           0.0           0.0           0.0          0.02];
julia> Z = Zonotope(c, G);
julia> cl = constraints_list(Z);
julia> remove_redundant_constraints(cl)
Error: primal simplex failed
```

I had a look at the implementation again and could not find an error in the code. Some of the constraints have a `b` value around 1e-6 (see below), which is close to the precision boundary of the solver. So I close this issue because we probably cannot change this behavior. The original problem has been solved.

```julia
10-element Vector{HalfSpace{Float64, Vector{Float64}}}:
 HalfSpace{Float64, Vector{Float64}}([0.0, -0.0, 0.0, -0.0, 1.0], 6.040000000000004)
 HalfSpace{Float64, Vector{Float64}}([-0.0, 0.0, -0.0, 0.0, -1.0], -6.0000000000000036)
 HalfSpace{Float64, Vector{Float64}}([-0.0010505239014466379, -0.023057281563153887, -0.052543778230130296, -0.9983518465630005, 0.0], -3.9783505817693245e-6)
 HalfSpace{Float64, Vector{Float64}}([0.0010505239014466379, 0.023057281563153887, 0.052543778230130296, 0.9983518465630005, -0.0], 3.980946831382166e-6)
 HalfSpace{Float64, Vector{Float64}}([0.015877774719621186, -0.014035025138108111, 0.7938688011892028, -0.6077197058165413, 0.0], 2.1880576332733115e-5)
 HalfSpace{Float64, Vector{Float64}}([-0.015877774719621186, 0.014035025138108111, -0.7938688011892028, 0.6077197058165413, -0.0], -2.1825011155940695e-5)
 HalfSpace{Float64, Vector{Float64}}([0.0010461339276099622, 0.023057540202451956, 0.05232428220860269, 0.9983633731938348, 0.0], 6.7494546259192395e-6)
 HalfSpace{Float64, Vector{Float64}}([-0.0010461339276099622, -0.023057540202451956, -0.05232428220860269, -0.9983633731938348, -0.0], -6.422393164341687e-6)
 HalfSpace{Float64, Vector{Float64}}([-0.01622601238355841, 0.013493428400992435, -0.8112851759572334, 0.5842696356855771, 0.0], -8.89610511700277e-5)
 HalfSpace{Float64, Vector{Float64}}([0.01622601238355841, -0.013493428400992435, 0.8112851759572334, -0.5842696356855771, -0.0], 9.277165155467405e-5)
```

**Closed by schillic** 2022-12-15 21:52 UTC
Labels: fix :face_with_head_bandage:
