### ISSUE TITLE
Random failure in polygon test

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2505] opened 2021-01-13 19:58 UTC
From https://ci.appveyor.com/project/mforets/lazysets-jl/builds/37250479,

```julia
LazySets.Polygon: Test Failed at C:\projects\lazysets-jl\test\unit_Polygon.jl:468
  Expression: n == length(p2.constraints) == length(po2.constraints) == length(po2.constraints)
   Evaluated: 4 == 5 == 5 == 5
Stacktrace:
 [1] top-level scope at C:\projects\lazysets-jl\test\unit_Polygon.jl:468
 [2] include(::String) at .\client.jl:439
 [3] macro expansion at C:\projects\lazysets-jl\test\runtests.jl:91 [inlined]
 [4] macro expansion at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Test\src\Test.jl:1113 [inlined]
 [5] macro expansion at C:\projects\lazysets-jl\test\runtests.jl:91 [inlined]
 [6] macro expansion at .\util.jl:175 [inlined]
 [7] top-level scope at C:\projects\lazysets-jl\test\runtests.jl:91
Test Summary:    | Pass  Fail  Total
LazySets.Polygon |  600     1    601
ERROR: LoadError: Some tests did not pass: 600 passed, 1 failed, 0 errored, 0 broken.
in expression starting at C:\projects\lazysets-jl\test\runtests.jl:67
ERROR: Package LazySets errored during testing
Stacktrace:
```
I suspect that's due to `rand` calls in

https://github.com/JuliaReach/LazySets.jl/blob/0360f186ca663ae97782dc3463fd3d59a5911372/test/unit_Polygon.jl#L461

So we may just use `using Random; Rand.seed!(1234)` somewhere in runtests.jl ?

**Comment by schillic** [comment] 2021-01-13 20:00
duplicate of #2426 ?

**Comment by mforets** [comment] 2021-01-13 20:09
ah, ok, you're saying it's a bug, i thought it was an simple issue with using `rand` with different seeds. i'll take a look..

**Closed** 2021-02-17 22:14 UTC
Labels: duplicate :two:
