### ISSUE TITLE
Plotting 1D HyperRectangles

### ISSUE THREAD

**Issue by chelseas** [JuliaReach/LazySets.jl#2656] opened 2021-04-13 03:43 UTC
I wasn't sure whether to open this issue in LazySets.jl or Plots.jl ¯\_(ツ)_/¯ 
But basically I'm having issues plotting 1D hyperrectangles as intervals.  

e.g. 

a = [array of 1D hyperrectangles]
using Plots
plotly()
Plots.plot(1:5, a)

where I want a plot that looks like this: 
https://invenia.github.io/Intervals.jl/stable/assets/HE.png

It says: 
ERROR: Cannot convert Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}} to series data for plotting

I've also tried passing an array of arrays, e.g.
[[h1], [h2], [h3], ...] where h1, h2, h3, etc. are hyperrectangles, 
because of suspicions that Plots.jl is treating the arguments as a series of "curves" to plot, but it produces the same message :'(

I also tried just doing this with intervals instead of hyperrects and get the same problem. i thought maybe that Plots.jl support Intervals.jl's Interval type but not the LazySets.Interval type?

Would love some guidance here, just want to plot some stuff ://

**Comment by schillic** [comment] 2021-04-13 04:54
Opening here was correct :+1:
It seems that the plot recipes for `1:5` (defined elsewhere) and `a` (defined here) cannot be combined. The problem is _probably_ that we do not offer the plot recipes in the correct way for such a combination. It might be a small fix but I am not sure _what_ to fix and how to find out (the plot recipe stuff is difficult to search for this piece of information).

Below is a possible workaround (defines 2D flat hyperrectangles which we know how to plot).

```julia
julia> using LazySets, Plots
julia> a = [Hyperrectangle([i + 0.5], [0.5]) for i in 1:5];
julia> plot(1:5, a)  # does not work

julia> b = [a[i] × Interval(i, i) for i in 1:5];
julia> plot(b)
```

If you want the same color, we are currently working on that in #2653. Then you can use `plot(b; same_recipe=true)`.

**Comment by mforets** [comment] 2021-04-13 18:57
Hi @chelseas,

I would also go for the approach of using the Cartesian product as suggested above. While `plot(1:5, a)` makes it more or less clear what you expect, it is particular to the case where the sets in the array `a` are 1-dimensional. It is less clear whether the elements should be centered around the integers or what convention to take exactly.

Think of `b = [a[i] × Interval(i, i) for i in 1:5];` as "lifting" the 1D sets to 2D sets. Then such plot recipe is implemented in this library. It is also possible to do `plot(a)`, but this plots them on the horizontal axis that plays the role of the real line.

**Comment by mforets** [comment] 2021-04-13 18:58
.. of course you can adjust the plot labels with any option available in the Plots.jl package.

**Comment by mforets** [comment] 2021-04-21 17:50
I'm closing the issue as it seems to be solved, but @chelseas don't hesitate to ask again if you have further inquiries!

**Closed by mforets** 2021-04-21 17:50 UTC
Labels: documentation :book:, plots :art:
