### ISSUE TITLE
Equivalence check for sets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1586] opened 2019-08-11 13:45 UTC
Add `isequivalent(X, Y) = X ⊆ Y && Y ⊆ X`, which is mainly supposed to be a convenience function.

For certain type combinations one can add more efficient methods later.

**Comment by schillic** [comment] 2019-09-14 14:12
Result of a discussion: we wanted to use `isapprox`, but that already exists (but talks about structural (approximate) equality, in contrast to semantic (approximate) equality as in `X ⊆ Y && Y ⊆ X`. One option might be to merge the existing implementation of `isapprox` into the implementation of `==` via an optional argument.

**Comment by mforets** [comment] 2019-09-14 14:19
cc: @ueliwechsler 

> I would suggest something like overloading Base.isequal and call == if the type of the arguments is identical.

The idea is good but i'm not totally convinced as `isequal` in Base does not use tolerances,

```julia
julia> isequal(0.0, -0.0)
false
```
In LazySets there's also the type-dependent, or structural, approximate comparison,

```julia
julia> B = BallInf([0.0, 0.0], 1.0)
BallInf{Float64}([0.0, 0.0], 1.0)

julia> B2 = BallInf([0.0, 0.0], 1.00000001)
BallInf{Float64}([0.0, 0.0], 1.00000001)

julia> B == B2
false

julia> B ≈ B2
true
```

Some options:

(1) Merge the existing implementation of `isapprox` into the implementation of `==` via an optional argument.
(2) Redefine `isapprox` with the dual inclusion method. Eventually add an optional algorithm that uses the current implementation.
(3) Think about a new function's name for the intended approximate checking that uses dual inclusion.

**Comment by ueliwechsler** [comment] 2019-09-22 10:40
If think the name suggestion from the original post `isequivalent` possibly with the operator `≡`  would work for option (3). Alternatively, one could say something more verbose like `contains_same_elements`, but I think `is_equivalent`  is already the right name.

Since this equivalence function should be a convenience function and does something different than `==` and `≈` which also checks for type equality, I prefer a clean new interface with a corresponding operator. Additionally, one could easily add more sophisticated ways to compute the equality of different types (e.g. two `HPolyhedron` without computing the support values twice).

**Comment by schillic** [comment] 2019-09-22 11:00
> possibly with the operator `≡`

I do not like this point because [`≡` is already an alias for `===`](https://docs.julialang.org/en/v1/base/base/#Core.:===).
The rest sounds good to me.

**Comment by ueliwechsler** [comment] 2019-12-03 14:51
During the implementation of the `is_equivalent` method, I stumbled upon this behaviour.
```julia
X = BallInf([0.1, 0.2, 0.1], 0.3)
Y = convert(HPolytope, X)
X ⊆ Y    # true
Y ⊆ X    # false
```
Is there a known reason for this behaviour?

**Comment by ueliwechsler** [comment] 2019-12-03 14:58
Additionally, I was wondering, if there should be also a relaxation of the `isequivalent` check, something like `isapproxequivalent` which is implemented as `X ⊆ Y  + BallInf(zeros(n),eps) && Y ⊆ X + BallInf(zeros(n),eps)`. The problem is, that for `HPolytopes` this needs `Polyhedra` to load to do the minkowski sum.

**Comment by mforets** [comment] 2019-12-03 15:01
> Is there a known reason for this behaviour?

Looks like it's a bug. I haven't seen in detail, but i would suspect that the comparisons being made in each case uses a different algorithm (that is OK as we dispatch on left and right arguments), but they are not using the same floating point tolerance. The transition from comparisons `a <= b` to comparisons with `._leq(a, b)` may not be all over the place in LazySets, as we have been doing this incrementally. However, it is very important to consider and give consistent results.

**Comment by schillic** [comment] 2019-12-03 15:36
> Additionally, I was wondering, if there should be also a relaxation of the `isequivalent` check, something like `isapproxequivalent`

Sure. This can also use the same method name by just adding an additional argument for the tolerance.

> which is implemented as `X ⊆ Y + BallInf(zeros(n),eps) && Y ⊆ X + BallInf(zeros(n),eps)`.

There should be another argument that controls the `p` norm of this ball. I am fine with `p = Inf` as the default.

> The problem is, that for `HPolytopes` this needs `Polyhedra` to load to do the minkowski sum.

I do not see a problem here. Additional requirements for additional functionality is fine.

**Comment by ueliwechsler** [comment] 2019-12-03 15:58
> Sure. This can also use the same method name by just adding an additional argument for the tolerance.

You mean, that there should be always a relaxation, but in the default case, the relaxation `eps=0`?

**Comment by schillic** [comment] 2019-12-03 16:00
For instance, but for `eps == 0` you should not create the sum with a zero ball of course.

**Comment by mforets** [comment] 2019-12-03 17:08
Inclusion checks on purpose already support using a custom tolerance, and they can be set by using `set_rtol`, see the docs [here](https://juliareach.github.io/LazySets.jl/dev/lib/comparisons/#LazySets.Tolerance). So there is no need for the Minkowski sum, as the inclusion checks should take care. I don't think that adding a new way to make the robust comparison is a good idea.

**Comment by schillic** [comment] 2019-12-03 17:09
> Inclusion checks on purpose already support using a custom tolerance, and they can be set by using `set_rtol`, see the docs [here](https://juliareach.github.io/LazySets.jl/dev/lib/comparisons/#LazySets.Tolerance). So there is no need for the Minkowski sum, as the inclusion checks should take care. I don't think that adding a new way to make the robust comparison is a good idea.

I was about to say that, so yeah, I agree that we should not add this option.

**Comment by mforets** [comment] 2019-12-03 17:10
.. or to reformulate my comment, is there a use case that is not handled as expected by `reltol`? Maybe there is, i don't know. I'm saying that a priori i would suggest to use `reltol` (which can be passed for convenience as a keyword argument to the new function, that's ok).

**Comment by ueliwechsler** [comment] 2019-12-03 22:32
I was not fully aware of the actual implementation of `set_rtol`. In this case, I don't think it makes sense to add a keyword argument. For now, I will just write a function which checks inclusion in both direction for two `LazySets` and if needed we can add more efficient implementations for specific types later on,.

**Comment by mforets** [comment] 2019-12-03 22:52
:+1:  Sounds like a good plan.

**Comment by ueliwechsler** [comment] 2019-12-03 22:53
> Looks like it's a bug

Btw, thanks for so quickly fixing the bug. 👍 ✨

**Comment by ueliwechsler** [comment] 2019-12-08 13:25
Before closing the issue, I was thinking about possible operators for the double inclusion test.
I know it's not that important, but I was still wondering if there exists an operator that would make sense.  What about any of these exotic operators? 😉
`A  ⫓  B`, `A  ⫅  B` or`A ⫉  B`

**Comment by schillic** [comment] 2019-12-08 15:04
A mathematician would just write `A == B`, but unfortunately this operator is already taken in this library.
`A ⫓ B` looks acceptable but I have never seen this operator, so I personally would still use `isequivalent`.
The other two operators indicate a one-directional meaning, which is why I do not like these.

**Comment by mforets** [comment] 2019-12-08 15:10
I agree with @schillic. On the other hand, i think that the symbol `≈` would be reasonable for the operation at hand, but [it is already taken](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Interfaces/LazySet.jl#L430)

**Comment by ueliwechsler** [comment] 2019-12-08 20:41
That reasoning makes sense to me 👍

**Closed** 2019-12-10 21:41 UTC
Labels: usability
