### ISSUE TITLE
Using constrainst in Zonotope -> HPolytope conversion

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1154] opened 2019-02-24 13:58 UTC
```julia
julia> using Test, Revise, LazySets, LinearAlgebra
julia> N = Float64;

julia> Z = Zonotope(zeros(N, 3), Matrix(N(1)*I, 3, 3))
Zonotope{Float64}([0.0, 0.0, 0.0], [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0])

julia> B = BallInf(zeros(N, 3), N(1)) # equivalent to Z
BallInf{Float64}([0.0, 0.0, 0.0], 1.0)

julia> @which convert(HPolytope, Z)
convert(::Type{HPolytope}, P::AbstractPolytope) in LazySets at /Users/forets/.julia/dev/LazySets/src/convert.jl:147
```

But it is in general more efficient to do `HPolytope(constraints_list(Z))`; i.e. use the `HPolyhedron` implementation:

```julia
function convert(::Type{HPolytope}, P::AbstractPolytope)
    return convert(HPolytope, convert(VPolytope, P))
end

function convert(::Type{HPolyhedron}, P::AbstractPolytope)
    return HPolyhedron(constraints_list(P))
end
```

Should we add a specific method 

```julia
function convert(::Type{HPolytope}, Z::Zonotope)
    return HPolytope(constraints_list(Z))
end
```

More generally, should we add a kwarg to `convert` such that it allows to choose the implementation?

**Comment by schillic** [comment] 2019-02-24 13:59
Duplicate of #932.

**Closed by schillic** 2019-02-24 13:59 UTC
