### ISSUE TITLE
Segfault when calling affine_map

### ISSUE THREAD

**Issue by castrong** [JuliaReach/LazySets.jl#2278] opened 2020-07-25 19:08 UTC
I'm running into an issue where I get a segfault when calling affine_map. I've reproduced the issue in the following code, where I create a weight matrix, bias matrix, and HPolytope and then call LazySets.affine_map with these. This leads to a segfault - I've pasted the output below the code.

```
using LazySets
using Polyhedra
using CDDLib

println("Creating weights and bias")
weights = [0.9115126809261311 0.4138440851467826 -0.33913105667038046 0.16700640073917672 -0.235120928568453; 0.6708292278443739 0.7576636017826068 0.8258791757476476 -0.17354379680520315 0.05393765869881095]
bias = [0.9457155975714278, 0.8338760871488544]

println("Creating polytope to affine map")
x_b = [0.0, 0.0, 48.84693391113945, -0.0, -0.0, -48.84693391113945, 1.8836929121889678, -185.48981164918555, -10.462945198060497, -1720.1125639313502, 30.8157991272438, 2.0328182777903794, -187.72706748216493, 31.333402600081193, 0.8311564016891444, -22.109210103545358, -1.5090925356292428, 24.84987253171124, 22.723250162485456, 46.839496529983926, -3.0989868675615497, 22.996310337995876, 7.619279109784628, -95.3486713467225, -7.854896717148563, 11.076982623957505, 13.357831143154556, 7.571546154878658, -103.47921230520559, 14.32831285002315, 8.135529620293468, 48.79574944863249, 19.26331941987261, 136.7074646969065, 737.0385026793365, 386.7092569137319, 35.510763078591076, 19.326340234088597, 19.984549508693096, 81.48499516064464, -13.09506164510387, -22.242599379716452, -16.602786452793474, -54.966447910936374, -66.1493435694213, -8.126647179260214, -72.17519884364094, -125.60015735472614, 0.0, 0.0, 0.0]
x_A = [-1.0 -0.0 -0.0 -0.0 -0.0; 0.0 0.0 -1.0 0.0 0.0; 0.0 8.076118521420486 0.0 35.19332258166109 13.837840646860146; 1.0 0.0 0.0 0.0 0.0; -0.0 -0.0 1.0 -0.0 -0.0; -0.0 -8.076118521420486 -0.0 -35.19332258166109 -13.837840646860146; -0.0 -3.183853894999074 -0.0 1.2556482650995342 -1.335269967575815; -0.0 -123.48562349701186 -0.0 12.461527940546762 -191.56298093458574; -0.0 -5.8754081576777555 -0.0 -1.0 -9.192156091705593; -0.0 -3954.019716077408 -0.0 516.3823227731308 1.0; -0.0 -2.020421677653688 -0.0 33.13501964692841 -1.5290182089446205; -0.0 -2.9367563418673024 -0.0 1.234074373666857 -1.3523486586045974; -0.0 -124.77068430216175 -0.0 12.582671668841833 -194.00279187884; -0.0 -1.7585066999570298 -0.0 33.51946010990651 -1.5485644695561085; -0.0 -7.218099737090482 -0.0 1.2632052067877908 1.0; -0.0 -15.488240849079062 -0.0 1.5412692709140638 -22.419938049751448; -0.0 -13.01835813695014 -0.0 1.0 4.926303512727481; -0.0 -7.412162155296751 -0.0 27.784232793846485 1.0; -0.0 13.01835813695014 -0.0 -1.0 -4.926303512727481; -0.0 15.488240849079062 -0.0 -1.5412692709140638 22.419938049751448; -0.0 7.412162155296751 -0.0 -27.784232793846485 -1.0; -0.0 13.401396607174302 -0.0 -1.0 -5.278131656113089; -0.0 7.243060544078956 -0.0 1.0 -6.770502738425847; -0.0 19.403024419575345 -0.0 1.0 -188.7132194712973; -0.0 -1.0 -0.0 -5.021202289034041 -3.6682709246498715; -0.0 34.39532800581566 -0.0 1.0 -38.624071876237714; -0.0 3.56454827656787 -0.0 12.19995345388215 -2.282505496082628; -0.0 6.8682285340371765 -0.0 1.0 -6.330770131793407; -0.0 18.257665816436887 -0.0 1.0 -200.17949584749525; -0.0 3.681583201082492 -0.0 13.127471771939016 -2.2825054960826288; -0.0 1.0 -0.0 5.021202289034041 3.6682709246498715; -0.0 8.076118521420485 -0.0 34.85346029447396 14.267156457625715; -0.0 5.8754081576777555 -0.0 1.0 9.192156091705593; -0.0 -18.257665816436887 -0.0 -1.0 200.17949584749525; -0.0 136.66235756616274 -0.0 1.0 985.1793220116999; -0.0 124.77068430216175 -0.0 -12.582671668841833 194.00279187884; -0.0 4.356246013730709 -0.0 1.0 36.423283339663975; -0.0 5.662649285509967 -0.0 1.0 14.188241938928781; -0.0 5.78278828756762 -0.0 1.0 15.078731703355606; -0.0 26.217307003486123 -0.0 -2.4420919880667333 41.45623389823421; -0.0 -3.681583201082492 -0.0 -13.127471771939016 2.2825054960826288; -0.0 -3.538269036057601 -0.0 -21.009712955831077 1.0; -0.0 1.7585066999570298 -0.0 -33.51946010990651 1.5485644695561085; -0.0 -6.767275556297155 -0.0 -60.347490188260586 1.0; -0.0 -5.913573386014781 -0.0 -73.97201065550148 -1.0; -0.0 -1.0 -0.0 -7.655047108966467 -1.0887090115595073; -0.0 -6.557924359755801 -0.0 -80.44710443760286 -1.0; -0.0 -6.004865949367552 -0.0 -164.54018450234872 1.0; -0.0 -1.0 -0.0 -0.0 -0.0; -0.0 -0.0 -0.0 -1.0 -0.0; -0.0 -0.0 -0.0 -0.0 -1.0]

x = LazySets.HPolytope(x_A, x_b)

println("Perform the affine map")
LazySets.affine_map(weights, x, bias)

```

**Output From Running Code**

Creating weights and bias
Creating polytope to affine map
Perform the affine map

signal (11): Segmentation fault: 11
in expression starting at /Users/castrong/Desktop/Research/NV_Fork/NeuralVerification.jl/examples/SimpleProblem.jl:27
ddf_BlockElimination at /Users/castrong/.julia/packages/CDDLib/Y6ywi/deps/usr/lib/libcddgmp.0.dylib (unknown line)
dd_blockelimination at /Users/castrong/.julia/packages/CDDLib/Y6ywi/src/CDDLib.jl:22 [inlined]
blockelimination at /Users/castrong/.julia/packages/CDDLib/Y6ywi/src/operations.jl:259
unknown function (ip: 0x126c85c99)
eliminate at /Users/castrong/.julia/packages/CDDLib/Y6ywi/src/polyhedron.jl:181
unknown function (ip: 0x126c853f9)
_linear_map_hrep at /Users/castrong/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractPolyhedron_functions.jl:768
_linear_map_hrep_helper at /Users/castrong/.julia/packages/LazySets/FwmiZ/src/Sets/HPolytope.jl:132
#linear_map#35 at /Users/castrong/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractPolyhedron_functions.jl:622
linear_map at /Users/castrong/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractPolyhedron_functions.jl:593 [inlined]
affine_map at /Users/castrong/.julia/packages/LazySets/FwmiZ/src/Interfaces/LazySet.jl:396
do_call at /Users/sabae/buildbot/worker/package_macos64/build/src/interpreter.c:323

**Comment by schillic** [comment] 2020-07-26 05:39
The weights matrix is 2x5, for which we use the `Polyhedra.BlockElimination` algorithm and the `CDDLib` LP solver by default.
The segmentation fault happens in `CDDLib`:
```julia
ddf_BlockElimination at .julia/packages/CDDLib/Y6ywi/deps/usr/lib/libcddgmp.0.dylib (unknown line)
dd_blockelimination at .julia/packages/CDDLib/Y6ywi/src/CDDLib.jl:22 [inlined]
```

A segfault is most probably not expected even for singular matrices, but I think we cannot help you here and you have to go up the stack to [`CDDLib`](https://github.com/JuliaPolyhedra/CDDLib.jl). I did not see anything obviously suspicious about the inputs, but I did not look very closely.

For nailing down the problem, go to [this line](https://github.com/JuliaReach/LazySets.jl/blob/046c7a85f0143bb65d0b44c279a8d4a1acde5db6/src/Interfaces/AbstractPolyhedron_functions.jl#L768)
```julia
.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractPolyhedron_functions.jl:768
```
either in a debugger or add some print output before that. `Phrep` is a `Polyhedra.polyhedron`, which is independent of `LazySets`. (Note that printing the polyhedron may take several minutes. This is a known issue.)

**Comment by mforets** [comment] 2020-07-26 06:14
Thanks for reporting. I can reproduce the error. We should report this upstream bug after getting a MWE.

---

Note that there are other ways to obtain the result, eg. by selecting the algorithm which uses the dual representation:

```julia
@time LazySets.translate(linear_map(weights, x, algorithm="vrep"), bias)
glp_simplex: unable to recover undefined or non-optimal solution
glp_simplex: unable to recover undefined or non-optimal solution
  0.038974 seconds (325.19 k allocations: 30.539 MiB)

VPolygon{Float64,Array{Float64,1}}([[1.1886110942098906, 1.1254318435663937], [1.2624991813433657, 1.2188890187654395], [1.3622548152869012, 1.4503183972450167]])
```
which you can convert back to hrep with `tohrep(..)`.

or if you don't need the exact result but are fine with using an overapproximation there are other ways, such as using  a zonotopic overapprox of the polytope, or using template approximation of the affine map. let me illustrate this last method. 

```julia
@time z = overapproximate(weights * x ⊕ bias, OctDirections(2))
  0.002423 seconds (917 allocations: 127.625 KiB)
```
or, since it's 2D, use a template using polar directions `PolarDirections(50)`

```julia
@time zp = overapproximate(weights * x ⊕ bias, PolarDirections(50));
  0.010374 seconds (5.46 k allocations: 779.312 KiB)

```
note that both cases are faster and more scalable than computing the result exactly because they don't need to pass to the dual rep of `x`.

![Screenshot from 2020-07-26 03-10-38](https://user-images.githubusercontent.com/12424594/88472850-bbb51800-ceed-11ea-90a8-db7d1dcdb654.png)

**Comment by castrong** [comment] 2020-07-27 07:51
Thanks for the suggestion on selecting the algorithm which uses the dual representation! I'll try that out tomorrow. Do you know why the "glp_simplex: unable to recover undefined or non-optimal solution" messages arise? Are they anything to worry about? 

We do need an exact result so unfortunately the over-approximations won't work in this context but it's good to know that they exist.

**Comment by mforets** [comment] 2020-07-29 13:28
> Do you know why the "glp_simplex: unable to recover undefined or non-optimal solution" messages arise? Are they anything to worry about?

i don't know. we should check if the solver status returned is optimal. also, this message is solver specific (GLPK in this case), and we can try to run the same computation with another solver.

**Comment by castrong** [comment] 2020-08-03 17:59
I just finished creating an example call calls directly to CDDLib.eliminate and have posted there. Is there anything else you'd recommend I look at to try to resolve this?

**Comment by mforets** [comment] 2020-08-04 12:40
> I just finished creating an example call calls directly to CDDLib.eliminate and have posted there. 

Nice, i think that's already quite useful :thumbsup: For easier reproducibility, you could also store `y_eq_Mx` and `Ax_leq_b` in a JLD2 file and upload a link to the file, together with your Project.toml and Manisfest.toml files. Are you familiar with Pkg environments?

**Comment by mforets** [comment] 2020-08-04 12:45
@castrong i tried to run the code https://github.com/JuliaPolyhedra/CDDLib.jl/issues/61#issue-672246657 on a fresh session, and:

- `I` is not defined, `using LinearAlgebra` on top should fix it
- the matrix `M` is not defined in `y_eq_Mx`, i guess that's the weights function
- the matri

**Comment by castrong** [comment] 2020-08-05 00:43
Thanks for those comments - I fixed the I and M issue (I hadn't run it on a fresh session so some things were still in scope). I'm not very familiar with Pkg environments but I would like to be. What should I know about them for this? Is the best way to link files through google drive or something like that?

**Comment by schillic** [comment] 2024-07-07 04:31
With the latest version of CDDLib, this does not throw a segfault anymore. The root cause is an error regarding numerical precision in CDDLib. Currently, the error message is misleading, but it is more informative than a segfault. Since we cannot do anything here, I close this issue.

**Closed by schillic** 2024-07-07 04:31 UTC
Labels: bug :bug:, external :outbox_tray:
