### ISSUE TITLE
MethodError in eps close approx of Bloating

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2894] opened 2021-10-28 17:26 UTC
Let

```julia
X = Bloating(ConvexHull(Hyperrectangle([1.0, 10.0, 0.0, 0.0], [0.1, 0.5, 0.5, 0.5]), LinearMap([0.8775705763029146 1.2241692374895278e-5 0.004794235068964515 2.05744097754082e-8; 1.2241692374895271e-5 0.9999875000518674 2.0574409775408196e-8 0.004999979166718595; -47.947144904139705 0.00479421449455474 0.8775705763029145 1.2241692374895276e-5; 0.004794214494554737 -0.004999958592308821 1.2241692374895275e-5 0.9999875000518672], Hyperrectangle([1.0, 10.0, 0.0, 0.0], [0.1, 0.5, 0.5, 0.5]))), 5.471231407473864e22, 2.0)
```

Then

```julia
overapproximate(Projection(X, [1, 3]), HPolygon, 1e-3)

MethodError: no method matching element(::Line2D{Float64, Vector{Float64}})
Closest candidates are:
  element(::Singleton) at /home/mforets/.julia/dev/LazySets/src/Sets/Singleton.jl:37
  element(::Singleton, ::Int64) at /home/mforets/.julia/dev/LazySets/src/Sets/Singleton.jl:55
  element(::ZeroSet{N}) where N at /home/mforets/.julia/dev/LazySets/src/Sets/ZeroSet.jl:43
  ...

Stacktrace:
 [1] new_approx(S::LinearMap{Float64, Bloating{Float64, ConvexHull{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, LinearMap{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, Float64, Matrix{Float64}}}}, Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}, p1::Vector{Float64}, d1::Vector{Float64}, p2::Vector{Float64}, d2::Vector{Float64})
   @ LazySets.Approximations ~/.julia/dev/LazySets/src/Approximations/iterative_refinement.jl:99
 [2] refine(approx::LazySets.Approximations.LocalApproximation{Float64, Vector{Float64}}, S::LinearMap{Float64, Bloating{Float64, ConvexHull{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, LinearMap{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, Float64, Matrix{Float64}}}}, Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}})
   @ LazySets.Approximations ~/.julia/dev/LazySets/src/Approximations/iterative_refinement.jl:150
 [3] _approximate(S::LinearMap{Float64, Bloating{Float64, ConvexHull{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, LinearMap{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, Float64, Matrix{Float64}}}}, Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}, ε::Float64)
   @ LazySets.Approximations ~/.julia/dev/LazySets/src/Approximations/iterative_refinement.jl:232
 [4] overapproximate(S::LinearMap{Float64, Bloating{Float64, ConvexHull{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, LinearMap{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, Float64, Matrix{Float64}}}}, Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}, ::Type{HPolygon}, ε::Float64; prune::Bool)
   @ LazySets.Approximations ~/.julia/dev/LazySets/src/Approximations/overapproximate.jl:97
 [5] overapproximate(S::LinearMap{Float64, Bloating{Float64, ConvexHull{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, LinearMap{Float64, Hyperrectangle{Float64, Vector{Float64}, Vector{Float64}}, Float64, Matrix{Float64}}}}, Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}, ::Type{HPolygon}, ε::Float64)
   @ LazySets.Approximations ~/.julia/dev/LazySets/src/Approximations/overapproximate.jl:87
 [6] top-level scope
   @ In[109]:1
 [7] eval
   @ ./boot.jl:373 [inlined]
 [8] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1196
```

**Comment by schillic** [comment] 2022-04-02 13:51
What happens here is that the approximation tries to compute the intersection of two line segments that are considered identical, so the result is not a point but a line segment.

```julia
julia> L1 = Line2D([1.0, 0.0], 5.471231407473864e22)
julia> L2 = Line2D([0.9999999999999958, 9.258726688644475e-8], 5.471231407473864e22)
julia> intersection(L1, L2)
Line2D{Float64, Vector{Float64}}([1.0, 0.0], 5.471231407473864e22)
```

The bloating here uses `ε = 5.471231407473864e22`. I suppose this is not really a value range where you should expect everything to go smoothly. In the approximation algorithm, a turn by a very small angle still gives very different points. We could review the way we choose these directions, but I am also fine if we close this issue.

https://github.com/JuliaReach/LazySets.jl/blob/fd40ceadcd90b785199793da167601727d863276/src/Approximations/iterative_refinement.jl#L92-L99

In our example we have:

```julia
norm(p1-p2, 2) == 5.06566362521282e15
_rtol(N) == 1.4901161193847656e-8
p1 == [5.471231407473864e22, 0.5]
p2 == [5.471231407473841e22, 5.065663625212814e15]
d1 == [1.0, 0.0]
d2 == [0.9999999999999958, 9.258726688644475e-8]
ndir == [0.9999999999999988, 4.636727611185042e-8]
```

**Comment by schillic** [comment] 2022-12-05 19:06
I close this since, as explained, I consider this a floating-point issue and not a bug in the code.

**Closed by schillic** 2022-12-05 19:06 UTC
Labels: bug :bug:
